# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: check-byte-order-marker
    - id: check-case-conflict
    - id: check-executables-have-shebangs
    - id: check-json
    - id: detect-private-key

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.13.1
    hooks:
      - id: gitlint
        stages: [commit-msg]

      - id: gitlint
        entry: gitlint --commits upstream/master..
        exclude: .*
        always_run: true
        stages: [manual]

  - repo: https://github.com/frnmst/md-toc
    rev: 7.0.2
    hooks:
      - id: md-toc
        args: [-p, --skip-lines, '1', commonmarker]

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.0
    hooks:
      - id: forbid-binary
        exclude: >
          (?x)^(
            ci/fixtures/one-byte-binary
          )$
        # - id: git-check  # Configure in .gitattributes
        #- id: git-dirty  # Configure in .gitignore
        #     - id: shellcheck
        #
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.7
    hooks:
      - id: forbid-crlf
      - id: forbid-tabs
