kind: Simple
apiVersion: k3d.io/v1alpha3
name: test
servers: 2
agents: 0
image: k3s:v1.22.3-k3s1
volumes:
- volume: /home/fred/k3s-config/:/var/lib/rancher/k3s/server/manifests/
  nodeFilters:
    - server:*
ports:
  - port: 5080:80
    nodeFilters:
      - loadbalancer
  - port: 5443:443
    nodeFilters:
      - loadbalancer
options:
  k3d:
    wait: true
    timeout: 2m0s
  k3s:
    extraArgs:
    - arg: --tls-san=192.168.0.150
      nodeFilters:
      - server:*
  kubeconfig:
    updateDefaultKubeconfig: true