apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    chart: nfs-subdir-external-provisioner-4.0.12
    heritage: Helm
    app: nfs-subdir-external-provisioner
    release: nfs-ext-provider
  name: nfs-client-retain
  annotations:
provisioner: cluster.local/nfs-ext-provider-nfs-subdir-external-provisioner
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  archiveOnDelete: "true"
